baseURL = "https://donbraulio.github.io/"
languageCode = 'en-us'
title = "Lamparilla 💡"


theme = "anubis2"

[languages]
	[languages.en]
		title = "Braulio Ríos - Development Blog"
		languageCode = "en-us"
		LanguageName = "🇺🇸EN"
		contentDir = "content"
		weight = 1
		[[languages.en.menus.main]]
			name = 'Home'
			pageRef = '/'
			weight = 1
		[[languages.en.menus.main]]
			name = 'Categories'
			pageRef = '/categories'
			weight = 2
		[[languages.en.menus.main]]
			name = 'Tags'
			pageRef = '/tags'
			weight = 3
		[[languages.en.menus.main]]
			name = 'Contact'
			pageRef = '/page/contact'
			weight = 4
        
[params]
copyright = "&#xA9; 2024 by Braulio Ríos. All Rights Reserved."
google_ad_client = "ca-pub-******"
ga4 = "G-******"
sharethis = ""

[outputs]
  home = ["HTML", "JSON"]
